version: "3.8"

volumes:
  rabbitmq_data:

services:
  ##################################
  # User: The User microservice
  ##################################
  user:
    build:
      context: user
      dockerfile: user.Dockerfile
    image: yuquanyeo/user:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/sb_user
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"


  ##################################
  # Homework: The Homework  microservice
  ##################################
  homework:
    build:
      context: homework
      dockerfile: homework.Dockerfile
    image: yuquanyeo/homework:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/sb_homework
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"


  ##################################
  # Liaise: The Liaise  microservice
  ##################################
  liaise:
    build:
      context: liaise
      dockerfile: liaise.Dockerfile
    image: yuquanyeo/liaise:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/sb_liaise
      PYTHONUNBUFFERED: 1
    ports:
      - "5200:5200"


  ##################################
  # Accept Offering: The Accept Offering microservice
  ##################################
  accept_offering:
    build:
      context: accept_offering
      dockerfile: accept_offering.Dockerfile
    image: yuquanyeo/accept_offering:esd
    restart: always
    depends_on:
      - homework
      - liaise
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      homework_URL: http://homework:5100/homework
      liaise_URL: http://liaise:5200/liaise
      PYTHONUNBUFFERED: 1
    ports:
      - "5300:5300"


  ##################################
  # Payment: The Payment microservice
  ##################################
  payment:
    build:
      context: payment
      dockerfile: payment.Dockerfile
    image: yuquanyeo/payment:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/sb_payment
      PYTHONUNBUFFERED: 1
    ports:
      - "5400:5400"


  ##################################
  # Make Payment: The Make Payment microservice
  ##################################
  make_payment:
    build:
      context: make_payment
      dockerfile: make_payment.Dockerfile
    image: yuquanyeo/make_payment:esd
    restart: always
    depends_on:
      - user
      - payment
      - accept_offering
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      user_URL: http://user:5000/user
      payment_URL: http://payment:5400/payment
      accept_offering_URL: http://accept_offering:5300/accept_offering
      PYTHONUNBUFFERED: 1
    ports:
      - "5500:5500"


  ##################################
  # Liaise Details: The Liaise Detail microservice
  ##################################
  liaise_detail:
    build:
      context: liaise_detail
      dockerfile: liaise_detail.Dockerfile
    image: yuquanyeo/liaise_detail:esd
    restart: always
    depends_on:
      - user
      - homework
      - liaise
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      user_URL: http://user:5000/user
      homework_URL: http://homework:5100/homework
      liaise_URL: http://liaise:5200/liaise
      liaise_detail_URL: http://liaise_detail:5600/liaise_detail
      PYTHONUNBUFFERED: 1
    ports:
      - "5600:5600"


  ##################################
  # Modify Homework: The Modify Homework microservice
  ##################################
  modify_homework:
    build:
      context: modify_homework
      dockerfile: modify_homework.Dockerfile
    image: yuquanyeo/modify_homework:esd
    restart: always
    depends_on:
      - homework
      - liaise
      - payment
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      homework_URL: http://homework:5100/homework
      liaise_URL: http://liaise:5200/liaise
      payment_URL: http://payment:5400/payment
      modify_homework: http://modify_homework:5700/modify_homework
      PYTHONUNBUFFERED: 1
    ports:
      - "5700:5700"

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

      
  ###################################
  # Error: The Error microservice
  ###################################
  error:
    build:
      context: amqp_error
      dockerfile: error.Dockerfile
    image: yuquanyeo/error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
